# https://hermes-agent.nousresearch.com/docs/user-guide/features/memory-providers
memory:
  provider: openviking
  write_approval: true

agent:
  api_max_retries: 3

  # https://hermes-agent.nousresearch.com/docs/reference/toolsets-reference
  enabled_toolsets: [
    "clarify", "todo",
    "delegation", "skills",
    "file", "terminal", "code_execution",
    "cronjob",
  ]

  # https://hermes-agent.nousresearch.com/docs/user-guide/configuration#tool-use-enforcement
  tool_use_enforcement: true

providers:
  openrouter-ai:
    base_url: https://openrouter.ai/api/v1
    key_env: OPENROUTER_AI_API_KEY
    request_timeout_seconds: 30
    stale_timeout_seconds: 30
    discover_models: false
    models:
      - z-ai/glm-5.3-flash
      - deepseek/deepseek-v4-flash-0731
      - poolside/laguna-s-2.1
      - upstage/solar-pro4
      - qwen/qwen3.8-flash

  router-ai:
    base_url: https://routerai.ru/api/v1
    key_env: ROUTER_AI_API_KEY
    request_timeout_seconds: 30
    stale_timeout_seconds: 30
    discover_models: false
    models:
      - z-ai/glm-5.3-flash
      - deepseek/deepseek-v4-flash-0731
      - poolside/laguna-s-2.1
      - upstage/solar-pro4
      - qwen/qwen3.8-flash

# https://hermes-agent.nousresearch.com/docs/user-guide/features/mixture-of-agents
moa:
  default_preset: i-router

  presets:
    i-openrouter:
      reference_models:
        - provider: custom:openrouter-ai
          model: poolside/laguna-s-2.1
          reasoning_effort: medium
        - provider: custom:openrouter-ai
          model: z-ai/glm-5.3-flash
          reasoning_effort: medium
      aggregator:
        provider: custom:openrouter-ai
        model: deepseek/deepseek-v4-flash-0731
        reasoning_effort: medium
      enabled: true

    i-router:
      reference_models:
        - provider: custom:router-ai
          model: qwen/qwen3.8-flash
          reasoning_effort: medium
        - provider: custom:router-ai
          model: deepseek/deepseek-v4-flash-0731
          reasoning_effort: medium
      aggregator:
        provider: custom:router-ai
        model: z-ai/glm-5.3-flash
        reasoning_effort: medium
      enabled: true

delegation:
  provider: custom:router-ai
  model: deepseek/deepseek-v4-flash-0731
  reasoning_effort: medium

model:
  provider: moa
  default: i-router

terminal:
  cwd: /code

mcp_servers:
  codegraph:
    command: "codegraph"
    args: ["serve", "--mcp"]

skills:
  external_dirs:
    - /skills
  write_approval: true

tool_loop_guardrails:
  hard_stop_enabled: true
  hard_stop_after:
    exact_failure: 3
    idempotent_no_progress: 3

compression:
  enabled: false

streaming:
  enabled: true
