[project]
name = "messoyakha-hermes-py"
dynamic = ["version", "dependencies"]
description = "..."
requires-python = ">=3.10,<4.0"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true
fallback-version = "0.0.0"

[tool.uv]
package = false

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "openviking>=0.4.17.1",
]

[tool.hatch.build.targets.wheel]
packages = ["scripts"]
