repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        exclude: .lock

  # https://github.com/astral-sh/ruff-pre-commit
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        language: system
        types: [ python ]
        entry: uv run ruff format
      - id: ruff-check
        name: ruff-isort
        language: system
        types: [ python ]
        entry: uv run ruff check --select I
        args: [--exit-non-zero-on-fix]
      - id: ruff-check
        name: ruff-lint
        language: system
        types: [ python ]
        entry: uv run ruff check --ignore I --unsafe-fixes
        args: [--exit-non-zero-on-fix]

  # https://github.com/facebook/pyrefly-pre-commit
  - repo: local
    hooks:
      - id: pyrefly-check
        name: pyrefly-check
        language: system
        entry: uv run pyrefly check
        pass_filenames: false
