[project]
name = "messoyakha-os"
version = "0.0.1"
description = "Personal financial environment for more effective risk management in order to make optimal decisions in the face of uncertainty."
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "attrs>=25.1.0,<26",
    "pydantic>=2.10.6,<3",
    "polars>=1.31.0",
    "pandas>=2.3.3",
    "pyarrow>=24.0.0",
    "loguru>=0.7.3,<0.8",
    "tqdm>=4.67.3",
    "pre-commit>=4.6.0",
    "ruff==0.14.8",
    "pyrefly==0.52.0",
]
requires-python = ">=3.10,<4.0"

[tool.uv]
package = false

# https://docs.astral.sh/uv/concepts/projects/workspaces/#workspace-sources
[tool.uv.sources]

# sys/kernel/py/*
messoyakha-coupling-py = { workspace = true }

# lib/py/*
messoyakha-binance-sdk-py = { workspace = true }
messoyakha-finam-sdk-py = { workspace = true }
messoyakha-s3-sdk-py = { workspace = true }

# home/idata/lib/*
messoyakha-cbr-sdk-py = { workspace = true }
messoyakha-dohod-sdk-py = { workspace = true }
messoyakha-fedstat-sdk-py = { workspace = true }
messoyakha-smart-lab-sdk-py = { workspace = true }

# home/idata/dags/*
messoyakha-dlh-py = { workspace = true }
messoyakha-dwh-py = { workspace = true }

# home/iquant/ad-hocs/*
messoyakha-test-strategy-py = { workspace = true }

[tool.uv.workspace]
members = [
    "home/idata/dags/*",
    "home/idata/lib/*",
    "home/iquant/ad-hocs/*",

    "lib/py/*",

    "sys/kernel/py/*",
]

[tool.ruff]
required-version = "0.14.8"
exclude = [".venv"]
line-length = 120
fix = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # https://docs.astral.sh/ruff/rules/any-type/
    "ANN002", "ANN003", "ANN401",

    # https://docs.astral.sh/ruff/rules/abstract-base-class-without-abstract-method/
    "B024",

    # https://docs.astral.sh/ruff/rules/missing-trailing-comma/
    "COM812",

    # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "D",

    # https://docs.astral.sh/ruff/rules/line-too-long/
    "E501",

    # https://docs.astral.sh/ruff/rules/f-string-in-exception/
    "EM101", "EM102",

    # https://docs.astral.sh/ruff/rules/commented-out-code/
    "ERA001",

    # https://docs.astral.sh/ruff/rules/#flake8-future-annotations-fa
    "FA",

    # https://docs.astral.sh/ruff/rules/#flake8-fixme-fix
    "FIX",

    # https://docs.astral.sh/ruff/rules/logging-f-string/
    "G004",

    # https://docs.astral.sh/ruff/rules/try-except-in-loop/
    "PERF203",

    # https://docs.astral.sh/ruff/rules/#refactor-plr
    "PLR0911", "PLR0912", "PLR0913", "PLR0915",

    # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    "RUF006",
    "RUF012",

    # https://docs.astral.sh/ruff/rules/hardcoded-sql-expression
    "S608",

    # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tc
    "TC001", "TC002", "TC003",

    # https://docs.astral.sh/ruff/rules/missing-todo-author/
    "TD002", "TD003",

    # https://docs.astral.sh/ruff/rules/raise-vanilla-args/
    "TRY003",

    # https://docs.astral.sh/ruff/rules/redundant-open-modes/
    "UP015",

    # https://docs.astral.sh/ruff/rules/tab-indentation/
    "W191"
]

[tool.ruff.lint.isort]
lines-after-imports = 2
split-on-trailing-comma = false
combine-as-imports = true
force-wrap-aliases = true

# https://docs.astral.sh/ruff/settings/#lint_isort_section-order
section-order = ["future", "standard-library", "third-party", "workspace", "first-party", "local-folder"]

# https://docs.astral.sh/ruff/settings/#lint_isort_sections
sections = { "workspace" = ["messoyakha_coupling", "messoyakha_binance_sdk", "messoyakha_finam_sdk", "messoyakha_s3_sdk", "messoyakha_cbr_sdk", "messoyakha_dohod_sdk", "messoyakha_fedstat_sdk", "messoyakha_smart_lab_sdk"] }
known-first-party = ["messoyakha_dlh", "messoyakha_dwh", "messoyakha_test_strategy"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-builtins]
ignorelist = ["id", "open", "type"]

[tool.ruff.lint.mccabe]
max-complexity = 15

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = false

[tool.pyrefly]
python-interpreter-path = ".venv/bin/python3.13"
python-platform = "linux"
search-path = [
    "sys/kernel/py/coupling",

    "lib/py/binance-sdk",
    "lib/py/finam-sdk",
    "lib/py/s3-sdk",

    "home/idata/lib/cbr-sdk",
    "home/idata/lib/dohod-sdk",
    "home/idata/lib/fedstat-sdk",
    "home/idata/lib/smart-lab-sdk",

    "home/idata/dags/dlh",
    "home/idata/dags/dwh",

    "home/iquant/ad-hocs/test-strategy"
]
