[project]
name = "messoyakha-smart-lab-sdk-py"
dynamic = ["version", "dependencies"]
description = "..."
requires-python = ">=3.10,<4.0"

[project.urls]
smart-lab-sectors = "https://smart-lab.ru/forum/sectors/"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true

[tool.uv]
package = true

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "crawlee[beautifulsoup,playwright]>=1.6.3",
    "httpx[http2]>=0.28.1,<0.29",
]

[tool.hatch.build.targets.wheel]
packages = ["messoyakha_smart_lab_sdk"]

[tool.hatch.build.targets.sdist]
exclude = ["tests"]
