[project]
name = "pep-crawlers"
dynamic = ["version", "dependencies"]
description = "..."
readme = "README.md"

requires-python = ">=3.10,<4.0"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true

[tool.uv]
package = true

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "crawlee>=1.6.0",
]

[tool.hatch.build.targets.wheel]
packages = ["pep_crawlers"]

[tool.hatch.build.targets.sdist]
exclude = ["tests"]
