[project]
name = "messoyakha-dlh-py"
dynamic = ["version", "dependencies"]
description = "..."

[project.urls]
habr-data-on-ice = "https://habr.com/ru/companies/selectel/articles/875472/"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true
fallback-version = "0.0.0"

[tool.uv]
package = true

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "dagster>=1.13.3",
    "dagster-pandera>=0.29.3",
    "that-depends>=3.9.2",
]

[tool.hatch.build.targets.wheel]
packages = ["messoyakha_dlh"]

[tool.hatch.build.targets.sdist]
exclude = ["tests"]
