[project]
name = "pep-pipelines"
dynamic = ["version", "dependencies"]
description = "..."
readme = "README.md"

requires-python = ">=3.10,<4.0"

[project.urls]
that-depends-quick-start = "https://that-depends.readthedocs.io/"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true

[tool.uv]
package = true

[tool.uv.sources]
pep-sdk = { workspace = true }

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "dagster>=1.13.3",
    "dagster-pandera>=0.29.3",
    "that-depends>=3.9.2",

    "fastparquet>=2026.3.0",

    "pep-sdk=={{ version }}",
]

[tool.hatch.build.targets.wheel]
packages = ["pep_pipelines"]

[tool.hatch.build.targets.sdist]
exclude = ["tests"]
