[project]
name = "pep-pipelines"
version = "0.0.1"
description = "..."
readme = "README.md"

requires-python = ">=3.10,<4.0"

[project.urls]
smart-lab-phor-dividends = "https://smart-lab.ru/q/phor/dividend/"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true

[tool.hatch.build.targets.wheel]
packages = ["pep_pipelines"]

[tool.hatch.build.targets.sdist]
exclude = ["tests"]
