[project]
name = "messoyakha-coupling-py"
dynamic = ["version", "dependencies"]
description = "..."
requires-python = ">=3.10,<4.0"

[project.urls]
habr-cohesion-and-coupling-the-difference = "https://habr.com/ru/articles/568216/"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["messoyakha_coupling"]

[tool.hatch.build.targets.sdist]
exclude = ["tests"]
