[project]
name = "pep-api"
dynamic = ["version", "dependencies"]
description = "..."
readme = "README.md"
requires-python = ">=3.10,<4.0"

[project.urls]
cbr = "https://www.cbr.ru/development/dws/"
cbrapi = "https://github.com/mbk-dev/cbrapi/tree/master"
okama = "https://habr.com/ru/companies/okama/profile/"
finam = "https://tradeapi.finam.ru/getting-started/"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true

[tool.uv]
package = true

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "httpx[http2]>=0.28.1,<0.29",
    "suds-py3>=1.4.5.0",
    "lxml>=6.1.0",
    "xlrd>=2.0.2",
]

[tool.hatch.build.targets.wheel]
packages = ["pep_api"]

[tool.hatch.build.targets.sdist]
exclude = ["tests"]
