[project]
name = "messoyakha-test-strategy-py"
dynamic = ["version", "dependencies"]
description = "..."
requires-python = ">=3.10,<4.0"

[project.urls]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true

[tool.uv]
package = true

[tool.uv.sources]
messoyakha-coupling-py = { workspace = true }
messoyakha-s3-sdk-py = { workspace = true }

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "dagster>=1.13.3",
    "dagster-pandera>=0.29.3",
    "that-depends>=3.9.2",

    "pyiceberg>=0.11.1",
    "pyiceberg-core>0.8.0",
    "fastparquet>=2026.3.0",

    "plotly>=6.7.0",
    "ipykernel>=7.2.0",
    "nbformat>=5.10.4",

    "messoyakha-coupling-py=={{ version }}",
    "messoyakha-s3-sdk-py=={{ version }}",
]

[tool.hatch.build.targets.wheel]
packages = ["messoyakha_test_strategy"]

[tool.hatch.build.targets.sdist]
exclude = ["tests"]
