[project]
name = "messoyakha-sdk-py"
dynamic = ["version", "dependencies"]
description = "..."

[project.urls]
habr-cohesion-and-coupling-the-difference = "https://habr.com/ru/articles/568216/"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning>=0.7.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true
fallback-version = "0.0.0"

[tool.uv]
package = true

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "httpx[http2]>=0.28.1,<0.29",
    "crawlee[beautifulsoup,playwright]>=1.6.3",
    "suds-py3>=1.4.5.0",
    "s3fs>=2023.6.0",
    "pyarrow>=24.0.0",
    "fastparquet>=2026.3.0",
]

[tool.hatch.build.targets.wheel]
packages = ["messoyakha_sdk"]

[tool.hatch.build.targets.sdist]
exclude = ["tests"]
